### ISSUE TITLE
min SDK

### ISSUE THREAD

**Issue by waj0** [SandroMachado/AndroidTampering#1]
Hi,
nice little library, great work.
It saved me time, already but I have one question:

Why is _minSdkVersion_ set to 16? This library (after rebuild) is working with SDK 10 like a charm. Please consider changing it.

**Comment by SandroMachado** [comment]
@waj0 thanks for the feedback. I will make a PR with this change! 
Thanks again!

**Comment by SandroMachado** [comment]
@waj0 The version `1.0.2` includes this fix. Thanks again.
