### ISSUE TITLE
How can I use this library?

### ISSUE THREAD

**Issue by pedrofsn** [SandroMachado/AndroidTampering#11]
I the README's code verification in my onCreate method on my GenericActivity (all activities extends of it).
When I'm developing the verification runs and my app closes. I think it's behavior is correct (is it?), so I wrap the code with something like "IS_DEBUG.not()" for the README's code verification just run on release APK. My app wil be only distributed (as release) in Google Play and on Crashlytics/Fabric/"Testflight" (as debug) for testers.

My idea of working with this library, is it correct? Or I need do something more?

**Comment by SandroMachado** [comment]
Hi @pedrofsn,
 
You need to define a point in your app when the check needs to be performed. Usually I use the splash-screen to check it.

Regards
