### ISSUE TITLE
log message not shown in logcat

### ISSUE THREAD

**Issue by waj0** [SandroMachado/AndroidTampering#5]
Hi, it's me again :)

I have a little problem with [this Log.d() statement](https://github.com/SandroMachado/AndroidTampering/blob/master/app/src/main/java/com/sandro/androidtampering/utils/AndroidTamperingProtectionUtils.java#L38). 

Logcat will not print that message for some reason. I did some testing and I think that first '\n' chars might be causing problems.

No problem with this log:
`Log.e("TAMPERING_PROTECTION", "_\n###" + Base64.encodeToString(md.digest(), Base64.DEFAULT) + "###_____");`
One more '\n' at the begining and log message is gone:
`Log.e("TAMPERING_PROTECTION", "\n_\n###" + Base64.encodeToString(md.digest(), Base64.DEFAULT) + "###_____");`

**Comment by SandroMachado** [comment]
@waj0 can you please provide more details. I am able to get it. Please see the screenshot.

![screen shot 2016-02-19 at 22 57 34](https://cloud.githubusercontent.com/assets/631739/13191528/50a6d220-d75c-11e5-935e-77737c0e9caa.png)

I just used this code to get the certificate signature.

```
AndroidTamperingProtectionUtils.getCertificateSignature(this);
```

**Comment by SandroMachado** [comment]
@waj0 you are right, it is not working for me using the library in the release configuration. I think the problem is related with the `\n`. I will try to fix this in the next release. Until then you can use this code:

``` Java
        try {
            PackageInfo packageInfo = context.getPackageManager().getPackageInfo(context.getPackageName(), PackageManager.GET_SIGNATURES);

            // The APK is signed with multiple signatures, probably it was tampered.
            if (packageInfo.signatures.length > 1) {
                return ;
            }

            for (Signature signature : packageInfo.signatures) {
                MessageDigest md = MessageDigest.getInstance("SHA");

                md.update(signature.toByteArray());

                Log.d("TAMPERING_PROTECTION", "___________" +  Base64.encodeToString(md.digest(), Base64.DEFAULT) + "___________");
            }
        } catch (Exception exception) {
            Log.d("TAMPERING_PROTECTION", exception.getStackTrace().toString());
        }
```

Thanks for the report!

**Comment by waj0** [comment]
Sorry for late answer, I was super busy last few weeks.

Version 1.0.3 is working perfectly for me, thanks.

**Comment by SandroMachado** [comment]
Great! thanks
