### ISSUE TITLE
Not installing

### ISSUE THREAD

**Issue by avipars** [SandroMachado/AndroidTampering#9]
I'm trying to add the compile line, but gradle gives me this error: 
First I tried, with the version in the README:     
compile 'com.github.SandroMachado:AndroidTampering:1.0.2'

And I got this error: Error:(53, 13) Failed to resolve: com.github.SandroMachado:AndroidTampering:1.02

Next, I tried with 1.0.3 and got the same error message.

**Comment by SandroMachado** [comment]
Hi @avipars,

did you add `Jitpack` to your maven repositories list?

``` 
	allprojects {
		repositories {
			...
			maven { url 'https://jitpack.io' }
		}
	}
```

**Comment by avipars** [comment]
K, so I am not sure what the issue was exactly, may have been the jitpack thing. In the end, i just copied the java classes, since it was just two, and put it in my app. It works well, but is annoying when I'm doing a debug build, so I removed it and will add it back right before a new release
